#内嵌服务器端口
server:
  port: 8016

#数据源配置 MyBatisConfig.class
spring:
  datasource:
    system:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://120.79.230.163:3306/wx?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
       username: root
       password: 123456
       # 使用druid数据源
       type: com.alibaba.druid.pool.DruidDataSource
       # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
       filters: stat,wall,log4j
       # 初始化大小，最小，最大
       initialSize: 5
       minIdle: 1
       maxActive: 20
       # 配置获取连接等待超时的时间
       maxWait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 300000
       validationQuery: SELECT 1 FROM DUAL
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       # 打开PSCache，并且指定每个连接上PSCache的大小
       poolPreparedStatements: true
       maxOpenPreparedStatements: 20
       connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
       # 合并多个DruidDataSource的监控数据
       useGlobalDataSourceStat: true

redis:
  database: 1
  minIdle: 5
  maxTotal: 500
  maxIdle: 100
  maxWaitMillis: 300
  testOnBorrow: true
  testOnReturn: true
  sentinelMaster: mymaster
  sentinelNodes: 120.79.230.163:6379
  host: 120.79.230.163
  port: 6379

#日志相关
logging:
  config: classpath:logback.xml

aliyunOss:
 endpoint: https://oss-cn-hangzhou.aliyuncs.com
 endpoints: https://www.akte.top
 accessKeyId: 111111
 accessKeySecret: 2222
 bucketName: wx